name: Docker Auto Publish

on:
  push:
    tags:
      - '*'

jobs:
  docker-auto-publish:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ 取回程式碼
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      # 2️⃣ 取得版本
      - name: Determine version
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      # 3️⃣ 設定 Docker build arguments
      - name: Set Docker build arguments
        id: docker-arg
        run: |
          IMAGE_BROWSER_VERSION=$(curl -s https://appversion.115.com/1/web/1.0/api/getMultiVer | jq -r '.data["Linux-115chrome"].version_code')
          IMAGE_CREATED=$(date -u -d '+8 hours' +"%Y-%m-%dT%H:%M:%SZ")
          echo "IMAGE_BROWSER_VERSION=$IMAGE_BROWSER_VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_CREATED=$IMAGE_CREATED" >> $GITHUB_OUTPUT

      # 4️⃣ 登入 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build 並推送版本 tag
      - name: Push version tag
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/115pc-docker:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/115pc-docker:latest
          build-args: |
            IMAGE_BROWSER_VERSION=${{ steps.docker-arg.outputs.IMAGE_BROWSER_VERSION }}
            IMAGE_CREATED=${{ steps.docker-arg.outputs.IMAGE_CREATED }}
