name: Docker Auto Publish

on:
  release:
    types: [published]

jobs:
  docker-auto-publish:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: 115pc-docker
    steps:
      # 1️⃣ 取回程式碼
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      # 2️⃣ 取得版本
      - name: Determine version
        id: version
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          VERSION=${TAG_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      # 3️⃣ 設定 Docker build arguments
      - name: Set Docker build arguments
        id: docker-arg
        run: |
          IMAGE_BROWSER_VERSION=$(cat BROWSER_VERSION)
          IMAGE_CREATED=$(TZ=Asia/Taipei date +"%Y-%m-%dT%H:%M:%SZ")
          echo "IMAGE_BROWSER_VERSION=$IMAGE_BROWSER_VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_BROWSER_VERSION=$IMAGE_BROWSER_VERSION"
          echo "IMAGE_CREATED=$IMAGE_CREATED" >> $GITHUB_OUTPUT
          echo "IMAGE_CREATED=$IMAGE_CREATED"

      # 4️⃣ 登入 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build 並推送版本 tag
      - name: Push version tag
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          build-args: |
            IMAGE_BROWSER_VERSION=${{ steps.docker-arg.outputs.IMAGE_BROWSER_VERSION }}
            IMAGE_CREATED=${{ steps.docker-arg.outputs.IMAGE_CREATED }}
