name: Release CI

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          release-type: simple
          target-branch: develop
  docker-publish:
    runs-on: ubuntu-latest
    needs: release-please
    env:
      DOCKER_IMAGE_NAME: 115pc-docker
    if: needs.release-please.outputs.release_created == 'true'
    steps:
      # 1️⃣ 取回程式碼
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: recursive

      # 2️⃣ 取得版本
      - name: Determine version
        id: version
        run: |
          VERSION=${{ needs.release-please.outputs.tag_name }}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"

      # 3️⃣ 設定 Docker build arguments
      - name: Set Docker build arguments
        id: docker-arg
        run: |
          IMAGE_BROWSER_VERSION=$(curl -s https://appversion.115.com/1/web/1.0/api/getMultiVer | jq -r '.data["Linux-115chrome"].version_code')
          IMAGE_CREATED=$(TZ=Asia/Taipei date +"%Y-%m-%dT%H:%M:%SZ")
          echo "IMAGE_BROWSER_VERSION=$IMAGE_BROWSER_VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_BROWSER_VERSION=$IMAGE_BROWSER_VERSION"
          echo "IMAGE_CREATED=$IMAGE_CREATED" >> $GITHUB_OUTPUT
          echo "IMAGE_CREATED=$IMAGE_CREATED"

      # 4️⃣ 登入 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 5️⃣ Build 並推送版本 tag
      - name: Push version tag
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          build-args: |
            IMAGE_BROWSER_VERSION=${{ steps.docker-arg.outputs.IMAGE_BROWSER_VERSION }}
            IMAGE_CREATED=${{ steps.docker-arg.outputs.IMAGE_CREATED }}
